---
- name: Harden and provision Docker host
  hosts: all
  become: true
  roles:
    - role: geerlingguy.security
    - role: geerlingguy.docker
    - role: nginx_site
      tags: nginx_site
    - role: landing_page
      tags: landing_page
