---
- name: Harden and provision Docker host
  hosts: all
  become: true
  roles:
    - role: geerlingguy.security
    - role: geerlingguy.docker
    - role: docker_compose_app
      tags: docker_compose_app
    - role: nginx_site
      tags: nginx_site
